### ISSUE TITLE
I need your help for porting TWRP

### ISSUE THREAD

**Issue by cobhc999** [Ryogo-Z/tolino_ntx_6sl_twrp#10]
Hello Ryogo-Z
you seem quite experienced with TWRP and E-Ink devices. I'm trying to port TWRP for a very special smartphone (Kingrow K1) which uses a e-ink screen. I managed to get the TWRP booting but it only show some black lines. I assume there is something missing regarding the e-ink display. Do you have any idea where to look at? I havnt found a way to contact you, thats why I write you here.

Were discussing the TWRP for that device on xda:
https://forum.xda-developers.com/project-treble/trebleenabled-device-questions-and-answers/kingrow-k1-eink-8-1-mediatek-helio-p23-t3935121

Regards - Timo

**Comment by Ryogo-X** [comment]
@cobhc999 I'm experienced mostly with devices that is based on i.MX6SL platform.
I can only give some general hints, because I'm not familiar with both MTK/e-ink and 8.1 boot process.

What you actually need to know and understand is that e-ink panel does not do refresh by itself, you need to trigger refresh explicitly every time. And to do that you will need to patch twrp code that works with fbdev.
For example, this is a patch which enabled triggering refresh of eink panel in TWRP for imx6sl platform: https://github.com/Ryogo-Z/tolino_ntx_6sl_twrp/blob/master/patches/e_ink_display.patch

Actual code you will need to add depends on the platform.

**Comment by Ryogo-X** [comment]
Does not directly relates to Tolino => closed.
