### ISSUE TITLE
tolino vison 2 root

### ISSUE THREAD

**Issue by creisey** [Ryogo-Z/tolino_ntx_6sl_twrp#17]
hi there, the twrp is working perfectly on the vision 2

but id like to root it to install other apps on it.

do you have some ideas how to do it?

my system is 11.2.3

i tried some stuff form this forum but i got a bootloop:

https://allesebook.de/anleitung/anleitung-tolino-vision-4-hd-root-zugriff-94665/

**Comment by bell07** [comment]
To install other apps you do not need root, but to enable adb access. Then you can install apk files trough usb.

As for bootloop I think you need to do a factory reset.

This repo is the wrong place for such questions because not TWRP related. Please ask in https://forum.alles-ebook.de/ forum.

If you are Linux-User, the method https://www.e-reader-forum.de/t/tolino-vision-2-rooten.147429/ is still valid even the latest 15.2.0 version

**Comment by Ryogo-X** [comment]
@bell07 thank you.
@creisey anyways, you can just search for SuperSu.zip and flash it from TWRP if you really need root. But, as @bell07 you don't really need root to install apps.
